version: '3.3'
services:
    proxy:
        image: caddy:latest
        ports:
            - 80:80
            - 443:443
        
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./localhost.pem:/etc/certs/localhost.crt
            - ./localhost-key.pem:/etc/certs/localhost.key

    web:
        image: nginx:latest